### ISSUE TITLE
Feature FTC: type checker Snowcat

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#350]
This is a meta-issue that summarizes the work to be done to make the type checker a fully-functional feature. All issues for this feature are labelled with [FTC-Snowcat](https://github.com/informalsystems/apalache/labels/FTC-Snowcat).

The user annotates some variable and operator declarations as specified in [ADR002](https://github.com/informalsystems/apalache/blob/unstable/docs/adr/002adr-types.md). The type checker either infers the types of all expressions and declarations in the specification or points to a type error.

- [x] java-like annotations in the comments, #226 and #262
- [x] integrate java-like annotations in the type checker, #504 
- [x] introduce type tags in TLA expressions, #561  
- [x] integrate with the model checker, #521: PRs #641, #632, #618, #650, #657, #658, #663, #668
- [x] update the manual, #688 
- [x] add types to the language manual, #547
- [x] write a tutorial, #689 
- [x] integrate TLC configs, #520 
- [x] fix numerous bug reports
- [ ] memo on the type checker, #905
- [x] fix instantiation of user-defined operators #869, #864, #953
- [ ] ~improve the expression builder framework~
  - [x] its own milestone: [Typed builder](https://github.com/informalsystems/apalache/milestone/62)
- [x] precise type checking for records: #401, #1151, #1170
- [x] introduce a few missing features: #570, #569
- [x] change the syntax for type aliases: #1843

**Comment by konnov** [comment]
Since most of the planned work has been done, I am closing this meta-issue. A few left-overs can be found in the [milestone 48](https://github.com/informalsystems/apalache/milestone/48). Also, unpinning this issue.
