### ISSUE TITLE
[FEATURE] Detect well-known unsupported features and point the user to workarounds

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#548]
Several language features appear quite often in our bug reports. As we cannot support these features in the near future, we should detect these patterns and point the user to the explanations and workaround in the documentation.

- [x] a..b for non-constant `a` and `b`: #425 
- [ ] CASE without OTHER: #285 
- [ ] Expanding sets of functions: #540

**Comment by lemmy** [comment]
FWIW:  You might want to propose your workaround to the PlusCal translator because it generates CASE without OTHER.

**Comment by konnov** [comment]
We have added a known issue on `a..b`. The other issues have been fixed, see #738 and #881.
