### ISSUE TITLE
[FEATURE] Use types to simplify `TypeOK`

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#723]
Blocked by [#401 Precise type checking for records](https://github.com/informalsystems/apalache/issues/401)

We should use type information to simplify membership tests such as `x \in BOOLEAN`, `x \in Int`, `x \in STRING`, `x \in Seq(...)`. By knowing the types, we could write a preprocessing pass that rewrites the above tests to `TRUE`, if the types are matching the tests.

- [x] `n \in Nat` (#1406)
- [x] `i \in Int, b \in BOOLEAN, \r \in Real` (#1406)
- [x] `seq \in Seq(_)` (#1406)
- [x] `fun \in [Int -> Int]` (#1443)
- [x] `<<{{1}}>> \in Seq(SUBSET Int)` or `{<<1>>} \in SUBSET (Seq(Int))` (#1443)
- [x] `tup \in S1 \X ... \X SN` (#1445)
- [x] records (#1453, blocked by #401 – maybe alternative solution in #1629)

**Comment by thpani** [comment]
@konnov What's a good place to implement this? `ExprOptimizer` or a separate transformation in `OptimizationPass` or ...?

**Comment by konnov** [comment]
I would implement a separate transformation similar to `ExprOptimizer`.

**Comment by thpani** [comment]
We should revisit this based on #1629

**Comment by konnov** [comment]
Do we handle the case `seq \in Seq(S)`, when `S` is a finite set, not `Int`, `Nat`, or `BOOLEAN`? I guess, we could translate it to `\A x \in DOMAIN seq: seq[x] \in S`.

**Comment by konnov** [comment]
Simplification for records should be unblocked now, since #401 is closed. Shall we revisit this issue any time soon?

**Comment by thpani** [comment]
> Simplification for records should be unblocked now, since #401 is closed. Shall we revisit this issue any time soon?

Does it make sense to follow up on this after we enable TypeSystem 1.2 by default in #1943?

**Comment by konnov** [comment]
Just labelled this one as unblocked.
